routes/web.php
        Route::group(['prefix' => 'tickets'], function () {
            Route::name('tickets.')->group(function () {
                Route::get('/', 'TicketController@index')->name('index');
                Route::get('/create', 'TicketController@create')->name('create');
                Route::post('/store', 'TicketController@store')->name('store');
                Route::get('/{id}', 'TicketController@show')->where('id', '[0-9]+')->name('show');
                Route::get('/{id}/edit', 'TicketController@edit')->name('edit');
                Route::patch('/{id}/update', 'TicketController@update')->name('update');
                Route::delete('/{id}/destroy', 'TicketController@destroy')->name('destroy');
                Route::post('/{id}/assign', 'TicketController@assign')->name('assign');
                Route::post('/{id}/unassign', 'TicketController@unassign')->name('unassign');
                Route::post('/{id}/close', 'TicketController@close')->name('close');
                Route::post('/attachments/{attachment}/download', 'TicketAttachmentController@download')->name('attachment.download');
            });
        });
    });

    /*
    |------------------------------------------
    | MediaHub (When Authorized)
    |------------------------------------------
    */
    Route::group(['prefix' => 'mediahub', 'middleware' => ['auth', 'twostep', 'banned'], 'namespace' => 'MediaHub'], function () {
        // MediaHub Home
        Route::get('/', 'HomeController@index')->name('mediahub.index');

        // Genres
        Route::get('/genres', 'GenreController@index')->name('mediahub.genres.index');

        // Genre
        Route::get('/genre/{id}', 'GenreController@show')->name('mediahub.genres.show');

        // Networks
        Route::get('/networks', 'NetworkController@index')->name('mediahub.networks.index');

        // Network
        Route::get('/network/{id}', 'NetworkController@show')->name('mediahub.networks.show');

        // Companies
        Route::get('/companies', 'CompanyController@index')->name('mediahub.companies.index');

        // Company
        Route::get('/company/{id}', 'CompanyController@show')->name('mediahub.companies.show');

        // TV Shows
        Route::get('/tv-shows', 'TvShowController@index')->name('mediahub.shows.index');

        // TV Show
        Route::get('/tv-show/{id}', 'TvShowController@show')->name('mediahub.shows.show');

        // TV Show Season
        Route::get('/tv-show/season/{id}', 'TvSeasonController@show')->name('mediahub.season.show');

        // Persons
        Route::get('/persons', 'PersonController@index')->name('mediahub.persons.index');

        // Person
        Route::get('/persons/{id}', 'PersonController@show')->name('mediahub.persons.show');

        // Collections
        Route::get('/collections', 'CollectionController@index')->name('mediahub.collections.index');

        // Collection
        Route::get('/collections/{id}', 'CollectionController@show')->name('mediahub.collections.show');

        // Movies
        Route::get('/movies', 'MovieController@index')->name('mediahub.movies.index');

        // Movie
        Route::get('/movies/{id}', 'MovieController@show')->name('mediahub.movies.show');
    });

    /*
    |---------------------------------------------------------------------------------
    | ChatBox Routes Group (When Authorized) (Alpha Ordered)
    |---------------------------------------------------------------------------------
    */
    Route::group(['prefix' => 'chatbox', 'middleware' => ['auth', 'twostep', 'banned'], 'namespace' => 'API'], function () {
        Route::get('/', 'ChatController@index');
        Route::get('/chatrooms', 'ChatController@fetchChatrooms');
        Route::post('/change-chatroom', 'ChatController@changeChatroom');
        Route::get('/messages', 'ChatController@fetchMessages');
        Route::post('/messages', 'ChatController@sendMessage');
    });

    /*
    |---------------------------------------------------------------------------------
    | Forums Routes Group (When Authorized) (Alpha Ordered)
    |---------------------------------------------------------------------------------
    */
    Route::group(['prefix' => 'forums', 'middleware' => ['auth', 'twostep', 'banned']], function () {
        // Forum System
        Route::name('forums.')->group(function () {
            Route::get('/', 'ForumController@index')->name('index');
            Route::get('/{id}', 'ForumController@show')->where('id', '[0-9]+')->name('show');
        });

        // Forum Category System
        Route::group(['prefix' => 'categories'], function () {
            Route::name('forums.categories.')->group(function () {
                Route::get('/{id}', 'ForumCategoryController@show')->where('id', '[0-9]+')->name('show');
            });
        });

        // Posts System
        Route::group(['prefix' => 'posts'], function () {
            Route::post('/topic/{id}/reply', 'PostController@reply')->name('forum_reply');
            Route::get('/posts/{id}/post-{postId}/edit', 'PostController@postEditForm')->name('forum_post_edit_form');
            Route::post('/posts/{postId}/edit', 'PostController@postEdit')->name('forum_post_edit');
            Route::get('/posts/{postId}/delete', 'PostController@postDelete')->name('forum_post_delete');
        });

        // Search Forums
        Route::get('/subscriptions', 'ForumController@subscriptions')->name('forum_subscriptions');
        Route::get('/latest/topics', 'ForumController@latestTopics')->name('forum_latest_topics');
        Route::get('/latest/posts', 'ForumController@latestPosts')->name('forum_latest_posts');
        Route::get('/search', 'ForumController@search')->name('forum_search_form');

        Route::group(['prefix' => 'topics'], function () {
            // Create New Topic
            Route::get('/forum/{id}/new-topic', 'TopicController@addForm')->name('forum_new_topic_form');
            Route::post('/forum/{id}/new-topic', 'TopicController@newTopic')->name('forum_new_topic');
            // View Topic
            Route::get('/{id}{page?}{post?}', 'TopicController@topic')->name('forum_topic');
            // Close Topic
            Route::get('/{id}/close', 'TopicController@closeTopic')->name('forum_close');
            // Open Topic
            Route::get('/{id}/open', 'TopicController@openTopic')->name('forum_open');
            //
            Route::post('/posts/tip_poster', 'BonusController@tipPoster')->name('tip_poster');

            // Edit Topic
            Route::get('/{id}/edit', 'TopicController@editForm')->name('forum_edit_topic_form');
            Route::post('/{id}/edit', 'TopicController@editTopic')->name('forum_edit_topic');
            // Delete Topic
            Route::get('/{id}/delete', 'TopicController@deleteTopic')->name('forum_delete_topic');
            // Pin Topic
            Route::get('/{id}/pin', 'TopicController@pinTopic')->name('forum_pin_topic');
            // Unpin Topic
            Route::get('/{id}/unpin', 'TopicController@unpinTopic')->name('forum_unpin_topic');
        });

        // Topic Label System
        Route::group(['prefix' => 'topics', 'middleware' => 'modo'], function () {
            Route::name('topics.')->group(function () {
                Route::get('/{id}/approve', 'TopicLabelController@approve')->name('approve');
                Route::get('/{id}/deny', 'TopicLabelController@deny')->name('deny');
                Route::get('/{id}/solve', 'TopicLabelController@solve')->name('solve');
                Route::get('/{id}/invalid', 'TopicLabelController@invalid')->name('invalid');
                Route::get('/{id}/bug', 'TopicLabelController@bug')->name('bug');
                Route::get('/{id}/suggest', 'TopicLabelController@suggest')->name('suggest');
                Route::get('/{id}/implement', 'TopicLabelController@implement')->name('implement');
            });
        });

        // Subscription System
        Route::get('/subscribe/topic/{route}.{topic}', 'SubscriptionController@subscribeTopic')->name('subscribe_topic');
        Route::get('/unsubscribe/topic/{route}.{topic}', 'SubscriptionController@unsubscribeTopic')->name('unsubscribe_topic');
        Route::get('/subscribe/forum/{route}.{forum}', 'SubscriptionController@subscribeForum')->name('subscribe_forum');
        Route::get('/unsubscribe/forum/{route}.{forum}', 'SubscriptionController@unsubscribeForum')->name('unsubscribe_forum');
    });

    /*
    |---------------------------------------------------------------------------------
    | Staff Dashboard Routes Group (When Authorized And A Staff Group) (Alpha Ordered)
    |---------------------------------------------------------------------------------
    */
    Route::group(['prefix' => 'dashboard', 'middleware' => ['auth', 'twostep', 'modo', 'banned'], 'namespace' => 'Staff'], function () {

        // Staff Dashboard
        Route::name('staff.dashboard.')->group(function () {
            Route::get('/', 'HomeController@index')->name('index');
        });

        // Articles System
        Route::group(['prefix' => 'articles'], function () {
            Route::name('staff.articles.')->group(function () {
                Route::get('/', 'ArticleController@index')->name('index');
                Route::get('/create', 'ArticleController@create')->name('create');
                Route::post('/store', 'ArticleController@store')->name('store');
                Route::get('/{id}/edit', 'ArticleController@edit')->name('edit');
                Route::post('/{id}/update', 'ArticleController@update')->name('update');
                Route::delete('/{id}/destroy', 'ArticleController@destroy')->name('destroy');
            });
        });

        // Applications System
        Route::group(['prefix' => 'applications'], function () {
            Route::name('staff.applications.')->group(function () {

resources/views/Staff/chat/room/chatroom_modals.blade.php
<div id="editChatroom-{{ $chatroom->id }}" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dark">
        <div class="modal-content">

            <div class="modal-header" style="text-align: center;">
                <h3>@lang('common.edit') @lang('common.chat-room') ({{ $chatroom->name }})</h3>
            </div>

            <form class="form-horizontal" role="form" method="POST"
                action="{{ route('staff.rooms.update', ['id' => $chatroom->id]) }}">
                @csrf
                <div class="modal-body" style="text-align: center;">
                    <h4>Please enter the new name you want to use for {{ $chatroom->name }}</h4>
                    <label for="chatroom_name"></label> <label for="name"></label><input
                        style="margin:0 auto; width:300px;" type="text" class="form-control" name="name" id="name"
                        placeholder="Enter @lang('common.name') Here..." value="{{ $chatroom->name }}" required>
                </div>

                <div class="modal-footer">
                    <button class="btn btn-md btn-default" data-dismiss="modal">@lang('common.cancel')</button>
                    <input class="btn btn-md btn-primary" type="submit">
                </div>
            </form>
        </div>
    </div>
</div>

<div id="deleteChatroom-{{ $chatroom->id }}" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dark">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">@lang('common.delete') Chatroom ({{ $chatroom->name }}) Permanently</h4>
            </div>

            <form class="form-horizontal" role="form" method="POST"
                action="{{ route('staff.rooms.destroy', ['id' => $chatroom->id]) }}">
                @csrf
                @method('DELETE')
                <div class="modal-body">
                    <p>Are you sure about this ?</p>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-md btn-default"
                        data-dismiss="modal">@lang('common.cancel')</button>
                    <input class="btn btn-md btn-danger" type="submit">
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Staff/chat/room/index.blade.php
@extends('layout.default')

@section('breadcrumb')
    <li>
        <a href="{{ route('staff.dashboard.index') }}" itemprop="url" class="l-breadcrumb-item-link">
            <span itemprop="title" class="l-breadcrumb-item-link-title">@lang('staff.staff-dashboard')</span>
        </a>
    </li>
    <li class="active">
        <a href="{{ route('staff.rooms.index') }}" itemprop="url" class="l-breadcrumb-item-link">
            <span itemprop="title" class="l-breadcrumb-item-link-title">@lang('common.chat-rooms')</span>
        </a>
    </li>
@endsection

@section('content')
    <div class="container box">
        <h2>@lang('common.chat-rooms')</h2>
    
        <button class="btn btn-primary" data-toggle="modal" data-target="#addChatroom">
            @lang('common.add') @lang('common.chat-room')
        </button>
        <div id="addChatroom" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-dark">
                <div class="modal-content">
    
                    <div class="modal-header" style="text-align: center;">
                        <h3>@lang('common.add') @lang('common.chat-room')</h3>
                    </div>
    
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('staff.rooms.store') }}">
                        @csrf
                        <div class="modal-body" style="text-align: center;">
                            <h4>Please enter the name of the chatroom you would like to create.</h4>
                            <label for="chatroom_name"> @lang('common.name'):</label> <label for="name"></label><input
                                style="margin:0 auto; width:300px;" type="text" class="form-control" name="name" id="name"
                                placeholder="Enter @lang('common.name') Here..." required>
                        </div>
    
                        <div class="modal-footer">
                            <button class="btn btn-md btn-default" data-dismiss="modal">@lang('common.cancel')</button>
                            <input class="btn btn-md btn-primary" type="submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    
        <div class="table-responsive">
            <table class="table table-condensed table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>@lang('common.name')</th>
                        <th>@lang('common.action')</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($chatrooms as $chatroom)
                        <tr>
                            <td>
                                {{ $chatroom->id }}
                            </td>
                            <td>
                                <a href="#">
                                    {{ $chatroom->name }}
                                </a>
                            </td>
                            <td>
                                <button class="btn btn-xs btn-warning" data-toggle="modal"
                                    data-target="#editChatroom-{{ $chatroom->id }}">
                                    <i class="{{ config('other.font-awesome') }} fa-pen-square"></i>
                                </button>
                                <button class="btn btn-xs btn-danger" data-toggle="modal"
                                    data-target="#deleteChatroom-{{ $chatroom->id }}">
                                    <i class="{{ config('other.font-awesome') }} fa-trash"></i>
                                </button>
                                @include('Staff.chat.room.chatroom_modals', ['chatroom' => $chatroom])
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection